from __future__ import annotations
import argparse, json
from common import load_json, save_json

MAP={
'ROUTING_AMBIGUITY':['ROUTING_DESCRIPTION_OR_MAP','MERGE_OR_NARROW_SKILLS','REGRESSION_FIXTURE'],
'CONTEXT_DISCOVERY':['SOURCE_OF_TRUTH_OR_GENERATED_DOC','TOOL_OR_ENVIRONMENT_CAPABILITY','REGRESSION_FIXTURE'],
'KNOWLEDGE_STALENESS':['SOURCE_OF_TRUTH_OR_GENERATED_DOC','MECHANICAL_CHECK','REGRESSION_FIXTURE'],
'MISSING_INVARIANT':['MECHANICAL_CHECK','AGENTS_INVARIANT','REGRESSION_FIXTURE'],
'DETERMINISTIC_REASONING_GAP':['MECHANICAL_CHECK','REGRESSION_FIXTURE'],
'TOOL_CAPABILITY_GAP':['TOOL_OR_ENVIRONMENT_CAPABILITY','REGRESSION_FIXTURE'],
'ENVIRONMENT_LEGIBILITY':['OBSERVABILITY_OR_INSPECTION_TOOL','TOOL_OR_ENVIRONMENT_CAPABILITY','REGRESSION_FIXTURE'],
'FEEDBACK_LOOP_GAP':['MECHANICAL_CHECK','REGRESSION_FIXTURE'],
'TEST_COVERAGE_GAP':['REGRESSION_FIXTURE','MECHANICAL_CHECK'],
'EVIDENCE_BINDING_GAP':['MECHANICAL_CHECK','REGRESSION_FIXTURE'],
'SAFETY_ENFORCEMENT_GAP':['FAIL_CLOSED_MECHANICAL_GATE','REGRESSION_FIXTURE'],
'SKILL_SCOPE_GAP':['UPDATE_EXISTING_SKILL','REGRESSION_FIXTURE'],
'SKILL_OVERLAP':['MERGE_OR_NARROW_SKILLS','ROUTING_DESCRIPTION_OR_MAP','REGRESSION_FIXTURE'],
'MODEL_INTERFACE_GAP':['STRUCTURED_SCHEMA_OR_OUTPUT','MECHANICAL_CHECK','REGRESSION_FIXTURE'],
'PROCESS_GAP':['ROUTING_DESCRIPTION_OR_MAP','UPDATE_EXISTING_SKILL','REGRESSION_FIXTURE']
}

def main():
    p=argparse.ArgumentParser(); p.add_argument('--classification',required=True); p.add_argument('--out'); a=p.parse_args()
    x=load_json(a.classification); cat=x.get('primary','UNCLASSIFIED')
    out={"classification":cat,"preferred_order":MAP.get(cat,['OTHER']),"rule":"Prefer the first control that fully covers the confirmed mechanism without unacceptable rigidity."}
    if a.out: save_json(a.out,out)
    else: print(json.dumps(out,indent=2))
if __name__=='__main__': main()
